
sequenceDiagram
    participant User
    participant Application
    participant FeedParser
    participant JobScheduler
    User->>Application: Add this new feed
    Application->>FeedParser: Get the `meta` for the feed and store it in the DB.
    FeedParser-->>Application: I'll do it asynchronously.
    Application->>JobScheduler: Add this new job to get the articles for the newly added feed and make this one high priority job.
    loop ScheduleJobs
        JobScheduler->>JobScheduler: Schedule the job queue
    end
    JobScheduler->>FeedParser: Hello Algorithm. I shall use your method to do what Application asked me to.
    JobScheduler-->>Application: I'll emit an updated event when I am done.
    Application-->>JobScheduler: I'll wait for you baby!
    Application-->>User: You'll get it soon brother.